export default  [
    {
        id:1,
        iconURL:"BitcoinIcon",
        cryptoName:"Bitcoin",
        abbr:"BTC",
        price:"$3,285,553.75",
        change:"+1.06%",
        marketCap:"$60.1T",
        isWatchlisted:false
    },
    {
        id:2,
        iconURL:"EthereumIcon",
        cryptoName:"Ethereum",
        abbr:"ETH",
        price:"$216,678,10",
        change:"-5.49%",
        marketCap:"$25.4T",
        isWatchlisted:false
    },
    {
        id:3,
        iconURL:"TetherIcon",
        cryptoName:"Tether",
        abbr:"USDT",
        price:"$74.31",
        change:"+0.11%",
        marketCap:"$4.6T",
        isWatchlisted:false
    },
    {
        id:4,
        iconURL:"CardanoIcon",
        cryptoName:"Cardano",
        abbr:"ADA",
        price:"$104.52",
        change:"-1.82%",
        marketCap:"$3.4T",
        isWatchlisted:false
    },
    {
        id:5,
        iconURL:"XRPIcon",
        cryptoName:"XRP",
        abbr:"XRP",
        price:"$57.21",
        change:"+1.11%",
        marketCap:"$2.7T",
        isWatchlisted:false
    },
    {
        id:6,
        iconURL:"DodgeIcon",
        cryptoName:"Dodge",
        abbr:"XRP",
        price:"$17.64",
        change:"-6.96%",
        marketCap:"$2.3T",
        isWatchlisted:false
    }
]